apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: test
spec:
  components:
    egressGateways:
    - enabled: true
      k8s:
        env:
        - name: CA_ADDR
          value: meshca.googleapis.com:443
